#This cloudbuld.yaml is going to build the docker container based on the Dockerfile.
#This file will be used by cloudbuild.

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'script'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq:$COMMIT_SHA', '.']



# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq:$COMMIT_SHA']



- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'crgcstobq'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '1'
    - '--allow-unauthenticated'
    - '--service-account'
    - $SERVICE_ACCOUNT_EMAIL
    - '--set-env-vars'
    - 'BUCKET_NAME=fileladingbucket_winged-app-429513-b8'
    - '--set-env-vars'
    - 'DATASET_ID =winged-app-429513-b8.stg_dataset'
    - '--set-env-vars'
    - 'TABLE_ID =winged-app-429513-b8.stg_dataset.landing_table'
    - '--set-env-vars'
    - 'LANDING_DATA =landing_data/'

 
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq'



options:
  logging: CLOUD_LOGGING_ONLY