#This cloudbuld.yaml is going to build the docker container based on the Dockerfile.
#This file will be used by cloudbuild.

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'script'
  # args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq:$COMMIT_SHA', '.']
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq1','.']



# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  # args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq:$COMMIT_SHA']
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/cr-gcs-to-bq/crgcstobq1']


options:
  logging: CLOUD_LOGGING_ONLY