#This cloudbuld.yaml is going to build the docker container based on the Dockerfile.
#This file will be used by cloudbuild.

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'script'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/crgcstobq:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/crgcstobq:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'cr-gcs-to-bq'
    - '--image'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/crgcstobq:$COMMIT_SHA'
    - '--region'
    - 'asia-south1'
    - '--platform'
    - 'managed'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '2'
    - '--allow-unauthenticated'
images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/my-docker-images-repo/crgcstobq:$COMMIT_SHA'