# This YAML file defines the Cloud Build configuration for your Cloud Run service.

# Define substitutions for sensitive information (replace with your values)
substitutions:
  _PROJECT_ID: winged-app-429513-b8  # Replace with your project ID

# Build steps
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$_PROJECT_ID/cloud-run-gcs-bigquery', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['push', 'gcr.io/$_PROJECT_ID/cloud-run-gcs-bigquery']
  # Add authentication using Cloud Build service account (optional)

# Optional: Artifact Pushing (if deploying to a different project)
# artifacts:
#   objects:
#     location: 'gs://your-bucket-name/path/to/artifacts'  # Replace with your bucket path
#     paths:
#       - 'gcr.io/$_PROJECT_ID/cloud-run-gcs-bigquery'

# Optional: Tags for deployments (replace with your deployment strategy)
# tags:
#   - gcr.io/$_PROJECT_ID/cloud-run-gcs-bigquery:latest

