name: Cloud Run Deploy workflow in develop branch

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: GCP Cloud Run Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json : '${{ secrets.GOOGLE_CREDENTIALS }}'
          project_id: "winged-app-429513-b8"


      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Deploy
        run: gcloud builds submit --config ./infra/cloudbuild.yml